### ISSUE TITLE
API-Key header invalid

### ISSUE THREAD

**Issue by ctciway** [ninoseki/uzen#401]
When I try to run a snapshot or load a yara rule. I get a "API-Key header invalid" error message.

**Comment by ninoseki** [comment]
Uzen has a very basic authentication through `api-key` header.

<img width="829" alt="Screen Shot 2021-05-29 at 2 51 32 PM" src="https://user-images.githubusercontent.com/291028/120059578-6c9bbe80-c08d-11eb-8ae0-59d1e775c72e.png">

The value is set via `GLOBAL_API_KEY` env. (The default value is `uzen`)

**Comment by ctciway** [comment]
Thank you.
