### ISSUE TITLE
Internal Server Error when running snapshot.

### ISSUE THREAD

**Issue by ctciway** [ninoseki/uzen#402]
Running on Docker. When I run a snapshot. I get the following error: Internal Server Error when running snapshot. 

And this is the logs on Docker.

uzen-2-2_worker_2 exited with code 1
worker_1    | 07:46:41: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 5 retries remaining...
worker_1    | 07:46:42: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 4 retries remaining...
worker_1    | 07:46:43: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 3 retries remaining...
worker_1    | 07:46:44: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 2 retries remaining...
worker_1    | 07:46:45: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 1 retries remaining...
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/bin/arq", line 8, in <module>
worker_1    |     sys.exit(cli())
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
worker_1    |     return self.main(*args, **kwargs)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
worker_1    |     rv = self.invoke(ctx)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
worker_1    |     return ctx.invoke(self.callback, **ctx.params)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
worker_1    |     return callback(*args, **kwargs)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/cli.py", line 48, in cli
worker_1    |     run_worker(worker_settings_, **kwargs)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/worker.py", line 756, in run_worker
worker_1    |     worker.run()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/worker.py", line 256, in run
worker_1    |     self.loop.run_until_complete(self.main_task)
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
worker_1    |     return future.result()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/worker.py", line 294, in main
worker_1    |     self._pool = await create_pool(
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
worker_1    |     return await create_pool(
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
worker_1    |     return await create_pool(
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
worker_1    |     return await create_pool(
worker_1    |   [Previous line repeated 2 more times]
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 230, in create_pool
worker_1    |     pool = await pool_factory(addr, db=settings.database, password=settings.password, encoding='utf8')
worker_1    |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 58, in create_pool
worker_1    |     await pool._fill_free(override_min=False)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 383, in _fill_free
worker_1    |     conn = await self._create_new_connection(self._address)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/aioredis/connection.py", line 111, in create_connection
worker_1    |     reader, writer = await asyncio.wait_for(open_connection(
worker_1    |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
worker_1    |     return fut.result()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/aioredis/stream.py", line 23, in open_connection
worker_1    |     transport, _ = await get_event_loop().create_connection(
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1017, in create_connection
worker_1    |     infos = await self._ensure_resolved(
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
worker_1    |     return await loop.getaddrinfo(host, port, family=family, type=type,
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
worker_1    |     return await self.run_in_executor(
worker_1    |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
worker_1    |     result = self.fn(*self.args, **self.kwargs)
worker_1    |   File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
worker_1    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
worker_1    | socket.gaierror: [Errno -2] Name or service not known
uzen_app    | redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 5 retries remaining...
uzen-2-2_worker_1 exited with code 1
uzen_app    | redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 4 retries remaining...
uzen_app    | redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 3 retries remaining...
uzen_app    | redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 2 retries remaining...
uzen_app    | redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 1 retries remaining...
uzen_app    | INFO:     172.20.0.1:62546 - "POST /api/snapshots/ HTTP/1.1" 500 Internal Server Error
uzen_app    | ERROR:    Exception in ASGI application
uzen_app    | Traceback (most recent call last):
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
uzen_app    |     result = await app(self.scope, self.receive, self.send)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
uzen_app    |     return await self.app(scope, receive, send)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
uzen_app    |     await super().__call__(scope, receive, send)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
uzen_app    |     await self.middleware_stack(scope, receive, send)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
uzen_app    |     raise exc from None
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
uzen_app    |     await self.app(scope, receive, _send)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 18, in __call__
uzen_app    |     await responder(scope, receive, send)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 35, in __call__
uzen_app    |     await self.app(scope, receive, self.send_with_gzip)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
uzen_app    |     raise exc from None
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
uzen_app    |     await self.app(scope, receive, sender)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
uzen_app    |     await route.handle(scope, receive, send)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
uzen_app    |     await self.app(scope, receive, send)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
uzen_app    |     response = await func(request)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in app
uzen_app    |     solved_result = await solve_dependencies(
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 544, in solve_dependencies
uzen_app    |     solved = await solve_generator(
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 462, in solve_generator
uzen_app    |     return await stack.enter_async_context(cm)
uzen_app    |   File "/usr/local/lib/python3.9/contextlib.py", line 556, in enter_async_context
uzen_app    |     result = await _cm_type.__aenter__(cm)
uzen_app    |   File "/usr/local/lib/python3.9/contextlib.py", line 175, in __aenter__
uzen_app    |     return await self.gen.__anext__()
uzen_app    |   File "./app/api/dependencies/arq.py", line 21, in get_arq_redis
uzen_app    |     async with get_arq_redis_with_context() as arq_redis:
uzen_app    |   File "/usr/local/lib/python3.9/contextlib.py", line 175, in __aenter__
uzen_app    |     return await self.gen.__anext__()
uzen_app    |   File "./app/api/dependencies/arq.py", line 11, in get_arq_redis_with_context
uzen_app    |     redis: ArqRedis = await create_pool(settings_=get_redis_settings())
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
uzen_app    |     return await create_pool(
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
uzen_app    |     return await create_pool(
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
uzen_app    |     return await create_pool(
uzen_app    |   [Previous line repeated 2 more times]
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 230, in create_pool
uzen_app    |     pool = await pool_factory(addr, db=settings.database, password=settings.password, encoding='utf8')
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 58, in create_pool
uzen_app    |     await pool._fill_free(override_min=False)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 383, in _fill_free
uzen_app    |     conn = await self._create_new_connection(self._address)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/aioredis/connection.py", line 111, in create_connection
uzen_app    |     reader, writer = await asyncio.wait_for(open_connection(
uzen_app    |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
uzen_app    |     return fut.result()
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/aioredis/stream.py", line 23, in open_connection
uzen_app    |     transport, _ = await get_event_loop().create_connection(
uzen_app    |   File "uvloop/loop.pyx", line 1956, in create_connection
uzen_app    |     ai_remote = f1.result()
uzen_app    | socket.gaierror: [Errno -2] Name or service not known

**Comment by ninoseki** [comment]
I believe you made a misconfiguration. 
Please review your `.env` and `docker-compose.yml`.
Also, I recommend you to learn Docker.

**Comment by ninoseki** [comment]
I will close this issue because there is no response for a month.
